modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "LGPL-3.0-or-later"

[[mods]]
modId = "yacl_test"
version = "1"
displayName = "YACL Test"
authors = "isXander"
description = '''
Test mod for YACL
'''
#logoFile = ""

[[dependencies.yacl_test]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yacl_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"
